spring.application.name=driver-service

server.port=8081

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=ridelink_driver

spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=ridelink_driver

jwt.secret=${JWT_SECRET}