spring.application.name=account-service

server.port=8080

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=ridelink_account

spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=ridelink_account

jwt.secret=${JWT_SECRET}