spring.application.name=fare-payment-service
server.port=8083

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=ridelink_fare

spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=ridelink_fare

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000