spring.application.name=ride-service

server.port=8082

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=ridelink_ride

driver.service.base-url=http://localhost:8081

driver.service.token=${DRIVER_SERVICE_TOKEN:}

fare.service.base-url=http://localhost:8083